micronaut:
  application:
    name: userService
  server:
    port: ${SERVER_PORT:8080}
datasources:
  default:
    url: jdbc:mysql://localhost:3306/gastos4
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
shedlock:
  defaults:
    lock-at-most-for: 1m